<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="EL2904_v0_00" Id="{8eea216c-65d1-4ea0-8eb8-d3ee8a85c501}">
    <Declaration><![CDATA[///EL2904 | 4-channel digital output terminal, TwinSAFE, 24 V DC, 0.5 A
FUNCTION_BLOCK EL2904_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>