<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="EL2262_v0_00" Id="{f1a00db0-a019-432b-8276-9926328701d1}">
    <Declaration><![CDATA[///EL2262 | XFC, 2-channel digital output terminal with oversampling
FUNCTION_BLOCK EL2262_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>