<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="EL2202_v0_00" Id="{9faa20a4-7a9a-4969-913b-a50e4ab982b9}">
    <Declaration><![CDATA[///EL2202 | XFC, 2-channel digital output terminal 24 V DC, TON/TOFF 1 µs, push-pull outputs, tri-state
FUNCTION_BLOCK EL2202_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>