include ${EPICS_ENV_PATH}/module.Makefile

EXCLUDE_ARCHS += eldk

SOURCES = \
  eemcuApp/src/eemcuAxis.cpp \
  eemcuApp/src/eemcuController.cpp \
  eemcuApp/src/eemcuMain.cpp

TEMPLATES = \
  eemcuApp/Db/eemcu.template \
  eemcuApp/Db/eemcu-extra.template

lint:
	
