include ${EPICS_ENV_PATH}/module.Makefile

SOURCES = \
  eemcuApp/src/eemcuAxis.cpp \
  eemcuApp/src/eemcuController.cpp \
  eemcuApp/src/eemcuMain.cpp

TEMPLATES = \
  eemcuApp/Db/eemcu.template \
  eemcuApp/Db/eemcu-extra.template

MISCS = \
  iocBoot/ioceemcu/SolAxis-48.cfg
