<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="EK1200" Id="{98544b5d-cfdf-476a-90c0-230bdaff0ec8}">
    <Declaration><![CDATA[FUNCTION_BLOCK EK1200
VAR_INPUT
	En: BOOL;
END_VAR
VAR_OUTPUT
	EnO: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[EnO:=En;
]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>