<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="EL1904_v0_00" Id="{f49a2add-59fa-42b6-a38c-ad08f54b3df1}">
    <Declaration><![CDATA[///EL1904 | 4-channel digital input terminal, TwinSAFE, 24 V DC
FUNCTION_BLOCK EL1904_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>