include ${EPICS_ENV_PATH}/module.Makefile

EXCLUDE_ARCHS += eldk

SOURCES = \
  TwinCATmotorApp/src/TwinCATmotorAxis.cpp \
  TwinCATmotorApp/src/TwinCATmotorController.cpp \
  TwinCATmotorApp/src/TwinCATmotorMain.cpp

TEMPLATES = \
  TwinCATmotorApp/Db/TwinCATmotor.template \
  TwinCATmotorApp/Db/TwinCATmotor-extra.template
