<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.0.25">
  <POU Name="EL2502_v0_00" Id="{bdbebb5e-656b-423d-b816-7055e429268d}">
    <Declaration><![CDATA[///EL2502 | 2-channel pulse width output terminal 24 V DC
FUNCTION_BLOCK EL2502_v0_00
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <ObjectProperties />
  </POU>
</TcPlcObject>